<?php

namespace Database\Seeders;

use App\Models\Company;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Company::query()->delete();
        DB::unprepared("INSERT INTO companies(id,slug,name) VALUES (470,'abbsy-indonesia-suplai','Abbsy Indonesia Suplai');
            INSERT INTO companies(id,slug,name) VALUES (2984,'abhinaya-prabawa-supala','Abhinaya Prabawa Supala');
            INSERT INTO companies(id,slug,name) VALUES (3003,'kanaya-abinaya-basupati','Kanaya Abinaya Basupati');
            INSERT INTO companies(id,slug,name) VALUES (6042,'garuda-super-accessories','Garuda Super Accessories');
            INSERT INTO companies(id,slug,name) VALUES (7128,'mulia-abadi-suplai','Mulia Abadi Suplai');
            INSERT INTO companies(id,slug,name) VALUES (7738,'acosta-super-food','Acosta Super Food');
            INSERT INTO companies(id,slug,name) VALUES (8299,'supri-jaya-abadi','Supri Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (8356,'adabul-good-supply','Adabul Good Supply');
            INSERT INTO companies(id,slug,name) VALUES (8850,'adamas-superindo','Adamas Superindo');
            INSERT INTO companies(id,slug,name) VALUES (9024,'adance-korsa-suplindo','Adance Korsa Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (9616,'superwira-abadi','Superwira Abadi');
            INSERT INTO companies(id,slug,name) VALUES (9918,'super-abadi-sakti','Super Abadi Sakti');
            INSERT INTO companies(id,slug,name) VALUES (10146,'superin-utama-adhesive','Superin Utama Adhesive');
            INSERT INTO companies(id,slug,name) VALUES (10254,'adib-global-food-supplies','Adib Global Food Supplies');
            INSERT INTO companies(id,slug,name) VALUES (11532,'suprima-mitra-adihusada','Suprima Mitra Adihusada');
            INSERT INTO companies(id,slug,name) VALUES (11799,'superuulkanin-adijaya','Superuulkanin Adijaya');
            INSERT INTO companies(id,slug,name) VALUES (11943,'supervulkanin-adijaya','Supervulkanin Adijaya');
            INSERT INTO companies(id,slug,name) VALUES (12172,'supra-adijaya-utama','Supra Adijaya Utama');
            INSERT INTO companies(id,slug,name) VALUES (12178,'supplindo-adijaya-internasional','Supplindo Adijaya Internasional');
            INSERT INTO companies(id,slug,name) VALUES (12408,'super-vulkanin-adijaya','Super Vulkanin Adijaya');
            INSERT INTO companies(id,slug,name) VALUES (13618,'adhi-suprasari-permai','Adhi Suprasari Permai');
            INSERT INTO companies(id,slug,name) VALUES (16096,'supin-adiyasa-agro-industri','Supin Adiyasa Agro Industri');
            INSERT INTO companies(id,slug,name) VALUES (16394,'adishree-blessindo-supernova','Adishree Blessindo Supernova');
            INSERT INTO companies(id,slug,name) VALUES (16511,'suprima-integrasi-adhi-pratama','Suprima Integrasi Adhi Pratama');
            INSERT INTO companies(id,slug,name) VALUES (17423,'supremefood-adil-sejahtera','Supremefood Adil Sejahtera');
            INSERT INTO companies(id,slug,name) VALUES (17922,'abadi-jaya-superfeed','Abadi Jaya Superfeed');
            INSERT INTO companies(id,slug,name) VALUES (17988,'superplast-adiperkasa-indonesia','Superplast Adiperkasa Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (18008,'royal-otentik-suplemen-aditif','Royal Otentik Suplemen Aditif');
            INSERT INTO companies(id,slug,name) VALUES (18691,'cakra-supra-aditia','Cakra Supra Aditia');
            INSERT INTO companies(id,slug,name) VALUES (18839,'buana-intisupply-aditama','Buana Intisupply Aditama');
            INSERT INTO companies(id,slug,name) VALUES (19791,'ading-supian-travel','Ading Supian Travel');
            INSERT INTO companies(id,slug,name) VALUES (20033,'supremie-pancamakmur-abadi','Supremie Pancamakmur Abadi');
            INSERT INTO companies(id,slug,name) VALUES (20115,'suprima-adirasa','Suprima Adirasa');
            INSERT INTO companies(id,slug,name) VALUES (20338,'optima-adinugraha-supra-lestari','Optima Adinugraha Supra Lestari');
            INSERT INTO companies(id,slug,name) VALUES (20388,'supra-rodatama-abadi','Supra Rodatama Abadi');
            INSERT INTO companies(id,slug,name) VALUES (20939,'adhidaya-suprakencana','Adhidaya Suprakencana');
            INSERT INTO companies(id,slug,name) VALUES (21217,'aditya-putra-supriyadi','Aditya Putra Supriyadi');
            INSERT INTO companies(id,slug,name) VALUES (24150,'super-lung-sentosa-abadi','Super Lung Sentosa Abadi');
            INSERT INTO companies(id,slug,name) VALUES (24373,'advance-technology-supplier','Advance Technology Supplier');
            INSERT INTO companies(id,slug,name) VALUES (24793,'supernet-advance-teknologi','Supernet Advance Teknologi');
            INSERT INTO companies(id,slug,name) VALUES (25413,'supra-advertising-nusantara','Supra Advertising Nusantara');
            INSERT INTO companies(id,slug,name) VALUES (25557,'supra-visual-advertensi','Supra Visual Advertensi');
            INSERT INTO companies(id,slug,name) VALUES (26336,'aneka-abadi-superindo','Aneka Abadi Superindo');
            INSERT INTO companies(id,slug,name) VALUES (27540,'aersupindo-abadi','Aersupindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (27557,'genera-aero-supply','Genera Aero Supply');
            INSERT INTO companies(id,slug,name) VALUES (27699,'ms-aero-support','Ms. Aero Support');
            INSERT INTO companies(id,slug,name) VALUES (27748,'multirindo-aero-support','Multirindo Aero Support');
            INSERT INTO companies(id,slug,name) VALUES (27759,'global-aero-support','Global Aero Support');
            INSERT INTO companies(id,slug,name) VALUES (27892,'aero-support-international','Aero Support International');
            INSERT INTO companies(id,slug,name) VALUES (27934,'mulrindo-aero-support','Mulrindo Aero Support');
            INSERT INTO companies(id,slug,name) VALUES (27941,'aero-support-nusantara','Aero Support Nusantara');
            INSERT INTO companies(id,slug,name) VALUES (28015,'supra-abadi-international','Supra Abadi International');
            INSERT INTO companies(id,slug,name) VALUES (28133,'delta-aerosupport','Delta Aerosupport');
            INSERT INTO companies(id,slug,name) VALUES (29556,'suprimindo-duta-abadi','Suprimindo  Duta Abadi');
            INSERT INTO companies(id,slug,name) VALUES (29641,'superindo-matra-abadi','Superindo Matra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (29796,'afrims-contractor-supplier','Afrims Contractor Supplier');
            INSERT INTO companies(id,slug,name) VALUES (29829,'aneka-abadi-suplindo','Aneka Abadi Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (29840,'super-asia-africa','Super Asia Africa');
            INSERT INTO companies(id,slug,name) VALUES (30135,'supalindo-sejahtera-abadi','Supalindo Sejahtera Abadi');
            INSERT INTO companies(id,slug,name) VALUES (30954,'aganilaya-suphala','Aganilaya Suphala');
            INSERT INTO companies(id,slug,name) VALUES (31121,'batam-agen-teknikal-suplai','Batam Agen Teknikal Suplai');
            INSERT INTO companies(id,slug,name) VALUES (31432,'super-agensi-indonesia','Super Agensi Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (31483,'united-supplies-agency','United Supplies Agency');
            INSERT INTO companies(id,slug,name) VALUES (31912,'aghist-mitra-suplindo','Aghist Mitra Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (32567,'sahabat-abadi-suplemindo','Sahabat Abadi Suplemindo');
            INSERT INTO companies(id,slug,name) VALUES (33999,'supra-agratamaindah','Supra Agratamaindah');
            INSERT INTO companies(id,slug,name) VALUES (34428,'organik-super-agro','Organik Super Agro');
            INSERT INTO companies(id,slug,name) VALUES (34668,'green-agro-supply-corporation','Green Agro Supply Corporation');
            INSERT INTO companies(id,slug,name) VALUES (35236,'bionik-super-agro','Bionik Super Agro');
            INSERT INTO companies(id,slug,name) VALUES (36479,'pasa-agro-supply','Pasa Agro Supply');
            INSERT INTO companies(id,slug,name) VALUES (36717,'agro-technical-supply','Agro Technical Supply');
            INSERT INTO companies(id,slug,name) VALUES (37482,'agus-supri-zatmikho','Agus Supri Zatmikho');
            INSERT INTO companies(id,slug,name) VALUES (38717,'supa-agro-teknologi','Supa Agro Teknologi');
            INSERT INTO companies(id,slug,name) VALUES (39116,'super-jaya-abadi','Super Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (42393,'wsi-agro-supergene','Wsi Agro Supergene');
            INSERT INTO companies(id,slug,name) VALUES (42849,'cahaya-abadi-super','Cahaya Abadi Super');
            INSERT INTO companies(id,slug,name) VALUES (43484,'superjasa-agung','Superjasa Agung');
            INSERT INTO companies(id,slug,name) VALUES (43911,'multi-supplier-agung-sentosa','Multi Supplier Agung Sentosa');
            INSERT INTO companies(id,slug,name) VALUES (44961,'supra-agung-palasari','Supra Agung Palasari');
            INSERT INTO companies(id,slug,name) VALUES (45368,'supratama-agro-sejahtera','Supratama Agro Sejahtera');
            INSERT INTO companies(id,slug,name) VALUES (45527,'supra-sentosa-agung','Supra Sentosa Agung');
            INSERT INTO companies(id,slug,name) VALUES (45530,'supra-mitra-agung','Supra Mitra Agung');
            INSERT INTO companies(id,slug,name) VALUES (47539,'indosupply-gemilang-abadi','Indosupply Gemilang Abadi');
            INSERT INTO companies(id,slug,name) VALUES (47993,'super-agro-nusantara','Super Agro Nusantara');
            INSERT INTO companies(id,slug,name) VALUES (48575,'supernal-waelala-agrotama','Supernal Waelala Agrotama');
            INSERT INTO companies(id,slug,name) VALUES (49789,'suprapto-sejahtera-abadi','Suprapto Sejahtera Abadi');
            INSERT INTO companies(id,slug,name) VALUES (50431,'suprim-agroniaga-pasifik','Suprim Agroniaga Pasifik');
            INSERT INTO companies(id,slug,name) VALUES (50541,'tekindo-agrotama-supply-company','Tekindo Agrotama Supply Company');
            INSERT INTO companies(id,slug,name) VALUES (51131,'ira-supra-agrobisnis','Ira Supra Agrobisnis');
            INSERT INTO companies(id,slug,name) VALUES (51250,'agrodaya-suprabumi','Agrodaya Suprabumi');
            INSERT INTO companies(id,slug,name) VALUES (51444,'supra-agung-permai','Supra Agung Permai');
            INSERT INTO companies(id,slug,name) VALUES (51697,'supra-agroniagatama','Supra Agroniagatama');
            INSERT INTO companies(id,slug,name) VALUES (53153,'asia-airindo-supply','Asia Airindo Supply');
            INSERT INTO companies(id,slug,name) VALUES (53212,'asia-airindo-suplly','Asia Airindo Suplly');
            INSERT INTO companies(id,slug,name) VALUES (54138,'super-aisindo-gemilang','Super Aisindo Gemilang');
            INSERT INTO companies(id,slug,name) VALUES (55150,'suprasentosa-agung','Suprasentosa Agung');
            INSERT INTO companies(id,slug,name) VALUES (55455,'suplindo-makmur-abadi','Suplindo Makmur Abadi');
            INSERT INTO companies(id,slug,name) VALUES (55723,'arbamin-nusantara-ajasupa','Arbamin Nusantara Ajasupa');
            INSERT INTO companies(id,slug,name) VALUES (56863,'supra-agung-perkasa','Supra Agung Perkasa');
            INSERT INTO companies(id,slug,name) VALUES (57466,'supra-agung-mitra-thama','Supra Agung Mitra Thama');
            INSERT INTO companies(id,slug,name) VALUES (58652,'suptafood-agung-perkasa','Suptafood Agung Perkasa');
            INSERT INTO companies(id,slug,name) VALUES (59270,'suprasejati-abadikarsa','Suprasejati Abadikarsa');
            INSERT INTO companies(id,slug,name) VALUES (60124,'supra-jaya-abadi','Supra Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (60575,'mega-akbar-superindo','Mega Akbar Superindo');
            INSERT INTO companies(id,slug,name) VALUES (60578,'supatra-akbar','Supatra Akbar');
            INSERT INTO companies(id,slug,name) VALUES (61327,'sahabat-abadi-supplindo','Sahabat Abadi Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (61360,'supreme-agung','Supreme Agung');
            INSERT INTO companies(id,slug,name) VALUES (62111,'akindo-supplies-indonesia','Akindo Supplies Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (62720,'akoh-engineering-supplies','Akoh Engineering & Supplies');
            INSERT INTO companies(id,slug,name) VALUES (63660,'superinfo-akselerasi-bisnis','Superinfo Akselerasi Bisnis');
            INSERT INTO companies(id,slug,name) VALUES (65269,'akurat-supramindo-konsul','Akurat Supramindo Konsul');
            INSERT INTO companies(id,slug,name) VALUES (65612,'alacrity-super-duper','Alacrity Super Duper');
            INSERT INTO companies(id,slug,name) VALUES (65790,'alarm-supplai-indonesia','Alarm Supplai Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (66003,'rabiya-alawiy-supriyadi-group','Rabiya Alawiy Supriyadi Group');
            INSERT INTO companies(id,slug,name) VALUES (66704,'alba-pelaut-suplay-dua','Alba Pelaut Suplay Dua');
            INSERT INTO companies(id,slug,name) VALUES (66745,'alba-pelaut-suplay','Alba Pelaut Suplay');
            INSERT INTO companies(id,slug,name) VALUES (68019,'aldaberta-enjiniring-dan-suplai','Aldaberta Enjiniring Dan Suplai');
            INSERT INTO companies(id,slug,name) VALUES (69469,'alexandra-alpha-supermarket','Alexandra Alpha Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (69876,'alfi-super-print','Alfi Super Print');
            INSERT INTO companies(id,slug,name) VALUES (71495,'pasuphati-alam-semesta','Pasuphati Alam Semesta');
            INSERT INTO companies(id,slug,name) VALUES (72311,'alfatih-jaya-yusup','Alfatih Jaya Yusup');
            INSERT INTO companies(id,slug,name) VALUES (72838,'aliga-super-power-indonesia-aspi','Aliga Super Power Indonesia Aspi');
            INSERT INTO companies(id,slug,name) VALUES (73607,'alam-supra-mandiri','Alam Supra Mandiri');
            INSERT INTO companies(id,slug,name) VALUES (73656,'super-indah-abadi','Super Indah Abadi');
            INSERT INTO companies(id,slug,name) VALUES (73664,'jawara-abadi-supertrans','Jawara Abadi Supertrans');
            INSERT INTO companies(id,slug,name) VALUES (74351,'alam-karunia-super-indonesia','Alam Karunia Super Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (76547,'jnw-alkes-supplier','Jnw Alkes Supplier');
            INSERT INTO companies(id,slug,name) VALUES (77539,'almira-supra-indah','Almira Supra Indah');
            INSERT INTO companies(id,slug,name) VALUES (77812,'tiarasuprindo-abadhi','Tiarasuprindo Abadhi');
            INSERT INTO companies(id,slug,name) VALUES (79179,'alora-superhitec','Alora Superhitec');
            INSERT INTO companies(id,slug,name) VALUES (79555,'alpha-beta-supply','Alpha Beta Supply');
            INSERT INTO companies(id,slug,name) VALUES (79776,'supra-alphaplus-handal','Supra Alphaplus Handal');
            INSERT INTO companies(id,slug,name) VALUES (80099,'surya-superkasa-abadi','Surya Superkasa Abadi');
            INSERT INTO companies(id,slug,name) VALUES (80144,'alpha-buana-supplies','Alpha Buana Supplies');
            INSERT INTO companies(id,slug,name) VALUES (80226,'alpha-dirga-supllytama','Alpha Dirga Supllytama');
            INSERT INTO companies(id,slug,name) VALUES (80683,'alpha-bravo-supply','Alpha Bravo Supply');
            INSERT INTO companies(id,slug,name) VALUES (80699,'angkasa-super-servis-alpha','Angkasa Super Servis Alpha');
            INSERT INTO companies(id,slug,name) VALUES (80706,'alrifara-indah-suplindo','Alrifara Indah Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (80801,'alphagraha-suplindokarsa','Alphagraha Suplindokarsa');
            INSERT INTO companies(id,slug,name) VALUES (81041,'superindo-alam-makmur','Superindo Alam Makmur');
            INSERT INTO companies(id,slug,name) VALUES (81147,'supra-makmur-abadi','Supra Makmur Abadi');
            INSERT INTO companies(id,slug,name) VALUES (81540,'supermustika-alam','Supermustika Alam');
            INSERT INTO companies(id,slug,name) VALUES (81866,'jari-alam-supatra','Jari Alam Supatra');
            INSERT INTO companies(id,slug,name) VALUES (82125,'alam-supitron-sakti','Alam Supitron Sakti');
            INSERT INTO companies(id,slug,name) VALUES (82329,'super-quality-makmur-abadi','Super Quality Makmur Abadi');
            INSERT INTO companies(id,slug,name) VALUES (82421,'altus-oil-and-gas-supply','Altus Oil And Gas Supply');
            INSERT INTO companies(id,slug,name) VALUES (82927,'supra-aluminium-industri','Supra Aluminium Industri');
            INSERT INTO companies(id,slug,name) VALUES (83023,'supreme-global-alumina','Supreme Global Alumina');
            INSERT INTO companies(id,slug,name) VALUES (83134,'sukses-aluminium-super','Sukses Aluminium Super');
            INSERT INTO companies(id,slug,name) VALUES (83147,'supreme-alumina-indonesia','Supreme Alumina Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (83271,'super-alumindo-eraperkasa','Super Alumindo Eraperkasa');
            INSERT INTO companies(id,slug,name) VALUES (83823,'supreme-alurodin','Supreme Alurodin');
            INSERT INTO companies(id,slug,name) VALUES (85809,'super-aman-llc','Super Aman Llc');
            INSERT INTO companies(id,slug,name) VALUES (88696,'pasuphati-alam-sejagad','Pasuphati Alam Sejagad');
            INSERT INTO companies(id,slug,name) VALUES (88697,'supreme-alam-resources','Supreme Alam Resources');
            INSERT INTO companies(id,slug,name) VALUES (91052,'amanah-supri-mandiri','Amanah Supri Mandiri');
            INSERT INTO companies(id,slug,name) VALUES (91549,'supreme-indo-american-industries','Supreme Indo-american Industries');
            INSERT INTO companies(id,slug,name) VALUES (91596,'suparos-amanah-jaya','Suparos Amanah Jaya');
            INSERT INTO companies(id,slug,name) VALUES (91826,'amanah-supplier-indonesia','Amanah Supplier Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (91929,'superkul-amerta-indonesia','Superkul Amerta Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (93990,'super-mitra-nusantara-abadi','Super Mitra Nusantara Abadi');
            INSERT INTO companies(id,slug,name) VALUES (94666,'supro-indonesia-amin','Supro Indonesia Amin');
            INSERT INTO companies(id,slug,name) VALUES (96140,'hardika-supra-abadi','Hardika Supra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (96699,'super-intermetal-abadi','Super Intermetal Abadi');
            INSERT INTO companies(id,slug,name) VALUES (97199,'amro-stelladuce-superblok','Amro Stelladuce Superblok');
            INSERT INTO companies(id,slug,name) VALUES (97550,'destakosuprindo-abadi','Destakosuprindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (99198,'anak-super-lele','Anak Super Lele');
            INSERT INTO companies(id,slug,name) VALUES (100099,'ananta-sinergi-suplai','Ananta Sinergi Suplai');
            INSERT INTO companies(id,slug,name) VALUES (100821,'anantarupa-yaesa-suptesu-jagarti','Anantarupa Yaesa Suptesu Jagarti');
            INSERT INTO companies(id,slug,name) VALUES (100865,'generasi-anak-super','Generasi Anak Super');
            INSERT INTO companies(id,slug,name) VALUES (102253,'supra-alam-lestari','Supra Alam Lestari');
            INSERT INTO companies(id,slug,name) VALUES (102293,'suplametindo-abadi','Suplametindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (102642,'citramitra-super-abadi','Citramitra Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (103585,'supra-intan-alam-putra','Supra Intan Alam Putra');
            INSERT INTO companies(id,slug,name) VALUES (103878,'alam-supelindo-abadi','Alam Supelindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (104050,'mitra-suplindo-abadi','Mitra Suplindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (104235,'supra-mitra-andalan','Supra Mitra Andalan');
            INSERT INTO companies(id,slug,name) VALUES (104828,'supra-andrawina-nusantara','Supra Andrawina Nusantara');
            INSERT INTO companies(id,slug,name) VALUES (104880,'andrawina-supra-sejahtera','Andrawina Supra Sejahtera');
            INSERT INTO companies(id,slug,name) VALUES (104882,'supra-andrawina-pratama','Supra Andrawina Pratama');
            INSERT INTO companies(id,slug,name) VALUES (104996,'andika-supra-tehnik','Andika Supra Tehnik');
            INSERT INTO companies(id,slug,name) VALUES (105362,'andromega-general-supplier','Andromega General Supplier');
            INSERT INTO companies(id,slug,name) VALUES (107139,'karina-andalan-supraprima','Karina Andalan Supraprima');
            INSERT INTO companies(id,slug,name) VALUES (107771,'supratama-aneka-industri-pma','Supratama Aneka Industri Pma');
            INSERT INTO companies(id,slug,name) VALUES (107972,'asia-superindo-indah-abadi','Asia Superindo Indah Abadi');
            INSERT INTO companies(id,slug,name) VALUES (108101,'miyoni-andaral-suplindo','Miyoni Andaral Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (108197,'andalan-prima-suplindo','Andalan Prima Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (108520,'anggun-suprabasari','Anggun Suprabasari');
            INSERT INTO companies(id,slug,name) VALUES (109645,'aneka-jaya-supermart','Aneka Jaya Supermart');
            INSERT INTO companies(id,slug,name) VALUES (109899,'super-andalas-permai','Super Andalas Permai');
            INSERT INTO companies(id,slug,name) VALUES (110664,'superkey-andalan-indonesia','Superkey Andalan Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (111001,'supra-tani-alam-raya','Supra Tani Alam Raya');
            INSERT INTO companies(id,slug,name) VALUES (111548,'super-andalas-plastik','Super Andalas Plastik');
            INSERT INTO companies(id,slug,name) VALUES (112196,'mercu-supra-abadi','Mercu Supra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (112497,'tomo-aneka-supply','Tomo Aneka Supply');
            INSERT INTO companies(id,slug,name) VALUES (112730,'aneka-superindo','Aneka Superindo');
            INSERT INTO companies(id,slug,name) VALUES (112764,'aneka-karya-supplyindo','Aneka Karya Supplyindo');
            INSERT INTO companies(id,slug,name) VALUES (112873,'supratama-aneka-industri','Supratama Aneka Industri');
            INSERT INTO companies(id,slug,name) VALUES (112940,'anekasuplindo-lestari','Anekasuplindo Lestari');
            INSERT INTO companies(id,slug,name) VALUES (113015,'dasasarana-aneka-supply','Dasasarana Aneka Supply');
            INSERT INTO companies(id,slug,name) VALUES (113155,'aneka-supply','Aneka Supply');
            INSERT INTO companies(id,slug,name) VALUES (113496,'aneka-baking-supplies','Aneka Baking Supplies');
            INSERT INTO companies(id,slug,name) VALUES (113546,'supra-anekaboga','Supra Anekaboga');
            INSERT INTO companies(id,slug,name) VALUES (113837,'super-bangunan-abadi','Super Bangunan Abadi');
            INSERT INTO companies(id,slug,name) VALUES (113962,'super-aneka-foods-and-beverages','Super Aneka Foods And Beverages');
            INSERT INTO companies(id,slug,name) VALUES (114749,'aneka-niaga-supermarket','Aneka Niaga Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (115001,'angeline-suparto-konsultan','Angeline Suparto Konsultan');
            INSERT INTO companies(id,slug,name) VALUES (115115,'andalan-pilar-supportindo-utama','Andalan Pilar Supportindo Utama');
            INSERT INTO companies(id,slug,name) VALUES (115255,'aneka-oil-seal-enginering-supply','Aneka Oil Seal Enginering Supply');
            INSERT INTO companies(id,slug,name) VALUES (115457,'anekaraya-supplindo','Anekaraya Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (115580,'angkasa-pura-suport','Angkasa Pura Suport');
            INSERT INTO companies(id,slug,name) VALUES (115971,'supra-andalan-bersama','Supra Andalan Bersama');
            INSERT INTO companies(id,slug,name) VALUES (116255,'super-andalas-steel','Super Andalas Steel');
            INSERT INTO companies(id,slug,name) VALUES (116424,'angkasa-super-servis-charlie','Angkasa Super Servis Charlie');
            INSERT INTO companies(id,slug,name) VALUES (117301,'angkasa-super-services','Angkasa Super Services');
            INSERT INTO companies(id,slug,name) VALUES (117850,'supra-andalassakti-lestari','Supra Andalassakti Lestari');
            INSERT INTO companies(id,slug,name) VALUES (119578,'angkasa-super-servis-beta','Angkasa Super Servis Beta');
            INSERT INTO companies(id,slug,name) VALUES (120586,'super-animasi-indonesia','Super Animasi Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (121245,'fas-angkasa-super','Fas Angkasa Super');
            INSERT INTO companies(id,slug,name) VALUES (121404,'supra-andalas-energy','Supra Andalas Energy');
            INSERT INTO companies(id,slug,name) VALUES (121423,'alamjaya-megasupply','Alamjaya Megasupply');
            INSERT INTO companies(id,slug,name) VALUES (121604,'aviatek-supportindo-angkasa','Aviatek Supportindo Angkasa');
            INSERT INTO companies(id,slug,name) VALUES (121922,'superbisnis-andalan-indonesia','Superbisnis Andalan Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (122051,'andalas-supply-base','Andalas Supply Base');
            INSERT INTO companies(id,slug,name) VALUES (122119,'indosupa-anjakerta','Indosupa Anjakerta');
            INSERT INTO companies(id,slug,name) VALUES (122840,'super-andalan-matematika','Super Andalan Matematika');
            INSERT INTO companies(id,slug,name) VALUES (122905,'triti-andaral-suplindo','Triti Andaral Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (123538,'andalan-super-prioritas','Andalan Super Prioritas');
            INSERT INTO companies(id,slug,name) VALUES (123823,'supra-nur-annisa','Supra Nur Annisa');
            INSERT INTO companies(id,slug,name) VALUES (123860,'annros-supra','Annros Supra');
            INSERT INTO companies(id,slug,name) VALUES (124002,'suprawira-andalas','Suprawira Andalas');
            INSERT INTO companies(id,slug,name) VALUES (124683,'anomi-event-support','Anomi Event Support');
            INSERT INTO companies(id,slug,name) VALUES (126293,'supplindo-jaya-abadi','Supplindo Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (127592,'antasena-energy-support','Antasena Energy Support');
            INSERT INTO companies(id,slug,name) VALUES (127747,'supra-kencana-abadi','Supra Kencana Abadi');
            INSERT INTO companies(id,slug,name) VALUES (128040,'antartika-suprateknik','Antartika Suprateknik');
            INSERT INTO companies(id,slug,name) VALUES (129554,'empat-super-abadi-international','Empat Super Abadi International');
            INSERT INTO companies(id,slug,name) VALUES (129642,'jaya-raya-super-abadi','Jaya Raya Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (130227,'super-sukses-anugerah','Super Sukses Anugerah');
            INSERT INTO companies(id,slug,name) VALUES (130415,'insuper-jaya-abadi','Insuper Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (131601,'enerindo-supra-abadi','Enerindo Supra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (131845,'apex-biocare-supplement','Apex Biocare Supplement');
            INSERT INTO companies(id,slug,name) VALUES (132623,'anugrah-daya-supplindo','Anugrah Daya Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (133023,'superindo-makmur-abadi','Superindo Makmur Abadi');
            INSERT INTO companies(id,slug,name) VALUES (135832,'super-sukses-abadi','Super Sukses Abadi');
            INSERT INTO companies(id,slug,name) VALUES (135963,'mariska-anugerah-suprajaya','Mariska Anugerah Suprajaya');
            INSERT INTO companies(id,slug,name) VALUES (137217,'gunung-super-aqua','Gunung Super Aqua');
            INSERT INTO companies(id,slug,name) VALUES (138501,'arah-supplies-prestasi-kolektif','Arah Supplies Prestasi Kolektif');
            INSERT INTO companies(id,slug,name) VALUES (139003,'makotadewa-araima-supiori','Makotadewa Araima Supiori');
            INSERT INTO companies(id,slug,name) VALUES (139004,'rut-araima-supiori','Rut Araima Supiori');
            INSERT INTO companies(id,slug,name) VALUES (140139,'anugrah-lestari-supindo','Anugrah Lestari Supindo');
            INSERT INTO companies(id,slug,name) VALUES (142756,'bina-area-support','Bina Area Support');
            INSERT INTO companies(id,slug,name) VALUES (143269,'supernova-esports-arena','Supernova Esports Arena');
            INSERT INTO companies(id,slug,name) VALUES (143418,'anugrah-karya-supa-mandiri','Anugrah Karya Supa Mandiri');
            INSERT INTO companies(id,slug,name) VALUES (143668,'gema-supra-abadi','Gema Supra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (145132,'suprakharisma-argakencana','Suprakharisma Argakencana');
            INSERT INTO companies(id,slug,name) VALUES (145168,'suprakharisma-graha-argakencana','Suprakharisma Graha Argakencana');
            INSERT INTO companies(id,slug,name) VALUES (146786,'supreme-jaya-abadi','Supreme Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (147270,'arista-prima-supertindo','Arista Prima Supertindo');
            INSERT INTO companies(id,slug,name) VALUES (148741,'arieza-kosmetika-suplemindo','Arieza Kosmetika Suplemindo');
            INSERT INTO companies(id,slug,name) VALUES (150354,'arkon-super-panel','Arkon Super Panel');
            INSERT INTO companies(id,slug,name) VALUES (150714,'anugrah-suputra-jaya','Anugrah Suputra Jaya');
            INSERT INTO companies(id,slug,name) VALUES (152332,'suparaja-armada-samudra','Suparaja Armada Samudra');
            INSERT INTO companies(id,slug,name) VALUES (152366,'arnaco-mitra-superintending','Arnaco Mitra Superintending');
            INSERT INTO companies(id,slug,name) VALUES (152823,'supradinamika-armada','Supradinamika Armada');
            INSERT INTO companies(id,slug,name) VALUES (153013,'bandar-armada-suplindo','Bandar Armada Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (153915,'anugrah-suplitindo-indonesia','Anugrah Suplitindo Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (153965,'pasundan-super-abadi','Pasundan Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (154561,'arsa-mega-supermarket','Arsa Mega Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (156044,'super-artemia-indo','Super Artemia Indo');
            INSERT INTO companies(id,slug,name) VALUES (157177,'suprasarana-media-artindo','Suprasarana Media Artindo');
            INSERT INTO companies(id,slug,name) VALUES (157379,'arto-supra-dinamika','Arto Supra Dinamika');
            INSERT INTO companies(id,slug,name) VALUES (157941,'salindra-suposai-abadi','Salindra Suposai Abadi');
            INSERT INTO companies(id,slug,name) VALUES (159288,'artha-perfoma-suplindo','Artha Perfoma Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (160286,'supreme-arta-fontana','Supreme Arta Fontana');
            INSERT INTO companies(id,slug,name) VALUES (160770,'unggul-super-artha','Unggul Super Artha');
            INSERT INTO companies(id,slug,name) VALUES (161202,'arus-deras-energy-supply','Arus Deras Energy Supply');
            INSERT INTO companies(id,slug,name) VALUES (161438,'superkrane-arta-utama','Superkrane Arta Utama');
            INSERT INTO companies(id,slug,name) VALUES (161949,'mulia-artha-suplindo','Mulia Artha Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (162146,'supra-arta-tunggal','Supra Arta Tunggal');
            INSERT INTO companies(id,slug,name) VALUES (162416,'aruziki-supplier-indo','Aruziki Supplier Indo');
            INSERT INTO companies(id,slug,name) VALUES (162979,'bank-perkreditan-rakyat-supra-wahana-arta','Bank Perkreditan Rakyat Supra Wahana Arta');
            INSERT INTO companies(id,slug,name) VALUES (163383,'atma-supala-artanti','Atma Supala Artanti');
            INSERT INTO companies(id,slug,name) VALUES (163692,'artha-mandiri-supply','Artha Mandiri Supply');
            INSERT INTO companies(id,slug,name) VALUES (163830,'supra-artatunggal','Supra Artatunggal');
            INSERT INTO companies(id,slug,name) VALUES (164101,'suptech-indotro-anugrah-pratama','Suptech Indotro Anugrah Pratama');
            INSERT INTO companies(id,slug,name) VALUES (164481,'bank-perkreditan-rakyat-supra-artapersada','Bank Perkreditan Rakyat Supra Artapersada');
            INSERT INTO companies(id,slug,name) VALUES (164542,'abaditra-buana-suprindo','Abaditra Buana Suprindo');
            INSERT INTO companies(id,slug,name) VALUES (164900,'supra-artamas-jaya','Supra Artamas Jaya');
            INSERT INTO companies(id,slug,name) VALUES (165284,'super-perdana-abadi','Super Perdana Abadi');
            INSERT INTO companies(id,slug,name) VALUES (166165,'arya-supra-nugraha','Arya Supra Nugraha');
            INSERT INTO companies(id,slug,name) VALUES (167341,'supi-arthagraha','Supi Arthagraha');
            INSERT INTO companies(id,slug,name) VALUES (167624,'arziqy-lestari-supplindo','Arziqy Lestari Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (168001,'aryasrina-supply','Aryasrina Supply');
            INSERT INTO companies(id,slug,name) VALUES (174855,'qardigair-suplai-asia','Qardigair Suplai Asia');
            INSERT INTO companies(id,slug,name) VALUES (174878,'supra-anugrah-natindo','Supra Anugrah Natindo');
            INSERT INTO companies(id,slug,name) VALUES (175175,'supreme-sports-asia','Supreme Sports Asia');
            INSERT INTO companies(id,slug,name) VALUES (176503,'supramas-arthasarana','Supramas Arthasarana');
            INSERT INTO companies(id,slug,name) VALUES (176703,'supratama-asia','Supratama Asia');
            INSERT INTO companies(id,slug,name) VALUES (176841,'anugrah-super','Anugrah Super');
            INSERT INTO companies(id,slug,name) VALUES (177752,'internasional-asia-supplier','Internasional Asia Supplier');
            INSERT INTO companies(id,slug,name) VALUES (178300,'delima-anugerah-suplindo','Delima Anugerah Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (179106,'anugerah-global-superintending','Anugerah Global Superintending');
            INSERT INTO companies(id,slug,name) VALUES (179532,'supra-artha-marindo','Supra Artha Marindo');
            INSERT INTO companies(id,slug,name) VALUES (179544,'super-artha-sentosa','Super Artha Sentosa');
            INSERT INTO companies(id,slug,name) VALUES (180764,'supala-jayasri-anugerah','Supala Jayasri Anugerah');
            INSERT INTO companies(id,slug,name) VALUES (181250,'eropa-asia-suplai-indonesia','Eropa Asia Suplai Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (182342,'asia-pasifik-superyachts-bali','Asia Pasifik Superyachts Bali');
            INSERT INTO companies(id,slug,name) VALUES (183010,'asia-super-cup','Asia Super Cup');
            INSERT INTO companies(id,slug,name) VALUES (183065,'asia-indonesia-mineral-suplai','Asia Indonesia Mineral Suplai');
            INSERT INTO companies(id,slug,name) VALUES (183790,'pan-asia-superintendence','Pan-asia Superintendence');
            INSERT INTO companies(id,slug,name) VALUES (183856,'synergy-anugrah-supply-indo','Synergy Anugrah Supply Indo');
            INSERT INTO companies(id,slug,name) VALUES (184266,'supra-aspindo-jaya','Supra Aspindo Jaya');
            INSERT INTO companies(id,slug,name) VALUES (185220,'artha-supremasi-teknologi','Artha Supremasi Teknologi');
            INSERT INTO companies(id,slug,name) VALUES (185426,'asia-pasific-superyachts-indonesia','Asia Pasific Superyachts Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (185857,'supa-cahaya-asia','Supa Cahaya Asia');
            INSERT INTO companies(id,slug,name) VALUES (186402,'auditel-support-asia','Auditel Support Asia');
            INSERT INTO companies(id,slug,name) VALUES (187316,'supramas-asri','Supramas Asri');
            INSERT INTO companies(id,slug,name) VALUES (188456,'sembakung-asri-supply','Sembakung Asri Supply');
            INSERT INTO companies(id,slug,name) VALUES (189951,'cipta-artha-supplindo','Cipta Artha Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (190347,'suprakharisma-multi-arthabahari','Suprakharisma Multi Arthabahari');
            INSERT INTO companies(id,slug,name) VALUES (190564,'superindo-asri','Superindo Asri');
            INSERT INTO companies(id,slug,name) VALUES (191234,'super-artha-gadai','Super Artha Gadai');
            INSERT INTO companies(id,slug,name) VALUES (191339,'mandala-asriboga-supplico','Mandala Asriboga Supplico');
            INSERT INTO companies(id,slug,name) VALUES (191537,'cakra-asia-suplindo','Cakra Asia Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (191957,'superindo-dynamic-asia','Superindo Dynamic Asia');
            INSERT INTO companies(id,slug,name) VALUES (195016,'astral-supplindo','Astral Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (196522,'general-supply-asia','General Supply Asia');
            INSERT INTO companies(id,slug,name) VALUES (196768,'super-anugerah-perkasa','Super Anugerah Perkasa');
            INSERT INTO companies(id,slug,name) VALUES (197078,'asia-ndt-laboratories-and-supplies','Asia Ndt Laboratories And Supplies');
            INSERT INTO companies(id,slug,name) VALUES (197470,'asta-tiga-superintendent','Asta Tiga Superintendent');
            INSERT INTO companies(id,slug,name) VALUES (198394,'supremasi-astadaya-sentosa','Supremasi Astadaya Sentosa');
            INSERT INTO companies(id,slug,name) VALUES (198419,'eventpro-support-asia','Eventpro Support Asia');
            INSERT INTO companies(id,slug,name) VALUES (198995,'zhafirah-supply-asia','Zhafirah Supply Asia');
            INSERT INTO companies(id,slug,name) VALUES (199325,'indonesia-super-asia','Indonesia Super Asia');
            INSERT INTO companies(id,slug,name) VALUES (201231,'berkat-abadi-supply','Berkat Abadi Supply');
            INSERT INTO companies(id,slug,name) VALUES (201623,'ateng-engineering-supplier','Ateng Engineering Supplier');
            INSERT INTO companies(id,slug,name) VALUES (203486,'muhendro-supaham-atmowijoyo','Muhendro Supaham Atmowijoyo');
            INSERT INTO companies(id,slug,name) VALUES (203488,'susilo-supaham-atmowijoyo','Susilo Supaham Atmowijoyo');
            INSERT INTO companies(id,slug,name) VALUES (203687,'super-natural-abadi','Super Natural Abadi');
            INSERT INTO companies(id,slug,name) VALUES (203932,'supra-atlas-mandiri','Supra Atlas Mandiri');
            INSERT INTO companies(id,slug,name) VALUES (205179,'attaya-metal-support','Attaya Metal Support');
            INSERT INTO companies(id,slug,name) VALUES (208220,'irgotama-supplindo-abadi','Irgotama Supplindo Abadi');
            INSERT INTO companies(id,slug,name) VALUES (209009,'supaflo-austekindo','Supaflo Austekindo');
            INSERT INTO companies(id,slug,name) VALUES (209498,'bekasi-auto-general-supplies','Bekasi Auto & General Supplies');
            INSERT INTO companies(id,slug,name) VALUES (209739,'sumber-makmur-auto-supply','Sumber Makmur Auto Supply');
            INSERT INTO companies(id,slug,name) VALUES (209771,'ganesha-electric-auto-supplies','Ganesha Electric Auto Supplies');
            INSERT INTO companies(id,slug,name) VALUES (209893,'super-anugerah-sejati','Super Anugerah Sejati');
            INSERT INTO companies(id,slug,name) VALUES (209936,'nhf-auto-supplies-indonesia','Nhf Auto Supplies Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (210078,'ausindo-food-supply','Ausindo Food Supply');
            INSERT INTO companies(id,slug,name) VALUES (210161,'berkat-auto-supply','Berkat Auto Supply');
            INSERT INTO companies(id,slug,name) VALUES (210199,'auto-supply-japan','Auto Supply Japan');
            INSERT INTO companies(id,slug,name) VALUES (210528,'glassy-auto-supplies','Glassy Auto Supplies');
            INSERT INTO companies(id,slug,name) VALUES (210681,'bhinneka-auto-suplai','Bhinneka Auto Suplai');
            INSERT INTO companies(id,slug,name) VALUES (210685,'supra-auto-bersama','Supra Auto Bersama');
            INSERT INTO companies(id,slug,name) VALUES (211043,'auxtec-supply-indonesia','Auxtec Supply Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (211070,'shiva-automotive-electric-supplies','Shiva Automotive Electric Supplies');
            INSERT INTO companies(id,slug,name) VALUES (211597,'autoseal-supra-international','Autoseal Supra International');
            INSERT INTO companies(id,slug,name) VALUES (212061,'supra-abadi-teknologi','Supra Abadi Teknologi');
            INSERT INTO companies(id,slug,name) VALUES (212714,'avicon-engineering-development-support','Avicon Engineering Development Support');
            INSERT INTO companies(id,slug,name) VALUES (213652,'aviando-sautma-supports','Aviando Sautma Supports');
            INSERT INTO companies(id,slug,name) VALUES (213804,'avian-superadhesive-indonesia','Avian Superadhesive Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (213829,'aviation-support-indonesia','Aviation Support Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (213881,'universal-aviation-support','Universal Aviation Support');
            INSERT INTO companies(id,slug,name) VALUES (214368,'superindo-anugrahbersama','Superindo Anugrahbersama');
            INSERT INTO companies(id,slug,name) VALUES (215524,'supra-baraya-abadi','Supra Baraya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (215683,'supra-awali','Supra Awali');
            INSERT INTO companies(id,slug,name) VALUES (217582,'axsuppot-maju-bersama','Axsuppot Maju Bersama');
            INSERT INTO companies(id,slug,name) VALUES (217771,'supra-mitra-abadi','Supra Mitra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (218080,'ayam-kampung-super-indonesia','Ayam Kampung Super Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (218276,'buah-super-abadi','Buah Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (220110,'supra-matra-abadi','Supra Matra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (223536,'bagtech-super-indonesia','Bagtech Super Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (223822,'superinti-bagusma','Superinti Bagusma');
            INSERT INTO companies(id,slug,name) VALUES (224199,'supertiwi-bagusma','Supertiwi Bagusma');
            INSERT INTO companies(id,slug,name) VALUES (224952,'nemesis-termite-baiting-and-supply','Nemesis Termite Baiting And Supply');
            INSERT INTO companies(id,slug,name) VALUES (225850,'raisyi-supplai-bahtera','Raisyi Supplai Bahtera');
            INSERT INTO companies(id,slug,name) VALUES (226751,'super-baja-jaya','Super Baja Jaya');
            INSERT INTO companies(id,slug,name) VALUES (227138,'supiori-sukses-abadi','Supiori Sukses Abadi');
            INSERT INTO companies(id,slug,name) VALUES (227513,'super-bahari-sejahtera','Super Bahari Sejahtera');
            INSERT INTO companies(id,slug,name) VALUES (227885,'infrasupport-mitra-abadi','Infrasupport Mitra Abadi');
            INSERT INTO companies(id,slug,name) VALUES (228716,'suprakharisma-budidaya-bahari','Suprakharisma Budidaya Bahari');
            INSERT INTO companies(id,slug,name) VALUES (228943,'superindo-baktipersada','Superindo Baktipersada');
            INSERT INTO companies(id,slug,name) VALUES (229242,'bakti-supran-pratama','Bakti Supran Pratama');
            INSERT INTO companies(id,slug,name) VALUES (229519,'inter-suplai-bakti','Inter Suplai Bakti');
            INSERT INTO companies(id,slug,name) VALUES (229710,'sinar-bakti-suppliers','Sinar Bakti Suppliers');
            INSERT INTO companies(id,slug,name) VALUES (230174,'super-save-elektronik-ballast','Super Save Elektronik Ballast');
            INSERT INTO companies(id,slug,name) VALUES (231203,'djaja-bakti-super','Djaja Bakti Super');
            INSERT INTO companies(id,slug,name) VALUES (231216,'supermutu-bajatama','Supermutu Bajatama');
            INSERT INTO companies(id,slug,name) VALUES (231257,'suprakharisma-baharilestari','Suprakharisma Baharilestari');
            INSERT INTO companies(id,slug,name) VALUES (232727,'super-bakeryindo-nusantara','Super Bakeryindo Nusantara');
            INSERT INTO companies(id,slug,name) VALUES (232780,'perseroan-dagang-industri-dan-pengangkutan-djaja-bakti-super','Perseroan Dagang, Industri Dan Pengangkutan Djaja Bakti Super');
            INSERT INTO companies(id,slug,name) VALUES (232915,'bakti-supraba','Bakti Supraba');
            INSERT INTO companies(id,slug,name) VALUES (233086,'tirta-jaya-bakti-super','Tirta Jaya Bakti Super');
            INSERT INTO companies(id,slug,name) VALUES (233402,'supriadi-cahaya-abadi','Supriadi Cahaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (233768,'bamm-super-desain','Bamm Super Desain');
            INSERT INTO companies(id,slug,name) VALUES (235506,'gemilang-supermarket-banjarbaru','Gemilang Supermarket Banjarbaru');
            INSERT INTO companies(id,slug,name) VALUES (235701,'pasupati-bali-prima','Pasupati Bali Prima');
            INSERT INTO companies(id,slug,name) VALUES (237643,'supra-bandar-internasional','Supra Bandar Internasional');
            INSERT INTO companies(id,slug,name) VALUES (238151,'supraco-kuala-bandar','Supraco Kuala Bandar');
            INSERT INTO companies(id,slug,name) VALUES (238570,'cip-bali-suplemen','Cip Bali Suplemen');
            INSERT INTO companies(id,slug,name) VALUES (239759,'suparco-kuala-bandar','Suparco Kuala Bandar');
            INSERT INTO companies(id,slug,name) VALUES (240074,'puspa-bandeng-super','Puspa Bandeng Super');
            INSERT INTO companies(id,slug,name) VALUES (240467,'reza-bahana-supplier','Reza Bahana Supplier');
            INSERT INTO companies(id,slug,name) VALUES (240586,'banama-equipment-support-indonesia','Banama Equipment Support Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (240648,'bali-indo-supplies','Bali Indo Supplies');
            INSERT INTO companies(id,slug,name) VALUES (241203,'bahari-prima-support','Bahari Prima Support');
            INSERT INTO companies(id,slug,name) VALUES (241810,'bahana-suprindo-kreasi','Bahana Suprindo Kreasi');
            INSERT INTO companies(id,slug,name) VALUES (241857,'bank-perkreditan-rakyat-supradanamas','Bank Perkreditan Rakyat Supradanamas');
            INSERT INTO companies(id,slug,name) VALUES (243488,'suputra-karya-bali','Suputra Karya Bali');
            INSERT INTO companies(id,slug,name) VALUES (243871,'bahana-suplindo','Bahana Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (244045,'bahana-super-logam','Bahana Super Logam');
            INSERT INTO companies(id,slug,name) VALUES (244223,'supra-flexindo-bali','Supra Flexindo Bali');
            INSERT INTO companies(id,slug,name) VALUES (245726,'suplai-bangun-propertindo','Suplai Bangun Propertindo');
            INSERT INTO companies(id,slug,name) VALUES (246836,'super-jaya-banteng','Super Jaya Banteng');
            INSERT INTO companies(id,slug,name) VALUES (247037,'sup-bali','Sup Bali');
            INSERT INTO companies(id,slug,name) VALUES (248106,'supra-bara-energi','Supra Bara Energi');
            INSERT INTO companies(id,slug,name) VALUES (249656,'pollux-barelang-megasuperblok','Pollux Barelang Megasuperblok');
            INSERT INTO companies(id,slug,name) VALUES (250587,'super-saku-bali','Super Saku Bali');
            INSERT INTO companies(id,slug,name) VALUES (252577,'supra-baru','Supra Baru');
            INSERT INTO companies(id,slug,name) VALUES (254341,'bali-super-bintang-persada','Bali Super Bintang Persada');
            INSERT INTO companies(id,slug,name) VALUES (256065,'supraperdana-baramasindo','Supraperdana Baramasindo');
            INSERT INTO companies(id,slug,name) VALUES (257058,'supreme-bersama-bali','Supreme Bersama Bali');
            INSERT INTO companies(id,slug,name) VALUES (258443,'supernova-project-bali','Supernova Project Bali');
            INSERT INTO companies(id,slug,name) VALUES (258758,'cahaya-baru-technikal-supply','Cahaya Baru Technikal Supply');
            INSERT INTO companies(id,slug,name) VALUES (259968,'barakka-supaja-makmur','Barakka Supaja Makmur');
            INSERT INTO companies(id,slug,name) VALUES (259992,'supiah-abadi','Supiah Abadi');
            INSERT INTO companies(id,slug,name) VALUES (260767,'bali-dewata-supermarket','Bali Dewata Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (260954,'munara-super-abadi','Munara Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (263794,'supply-indotama-base','Supply Indotama Base');
            INSERT INTO companies(id,slug,name) VALUES (263801,'jambi-supply-base','Jambi Supply Base');
            INSERT INTO companies(id,slug,name) VALUES (263821,'supply-base-coalindo','Supply Base Coalindo');
            INSERT INTO companies(id,slug,name) VALUES (263832,'supply-base-cemerlang','Supply Base Cemerlang');
            INSERT INTO companies(id,slug,name) VALUES (263856,'tuban-supply-base','Tuban Supply Base');
            INSERT INTO companies(id,slug,name) VALUES (264842,'tri-ollah-bangun-construction-supplies','Tri Ollah Bangun Construction Supplies');
            INSERT INTO companies(id,slug,name) VALUES (265603,'daya-bangkit-suportindo','Daya Bangkit Suportindo');
            INSERT INTO companies(id,slug,name) VALUES (266380,'indonesia-superior-baterai','Indonesia Superior Baterai');
            INSERT INTO companies(id,slug,name) VALUES (266754,'bali-business-supplies','Bali Business Supplies');
            INSERT INTO companies(id,slug,name) VALUES (266874,'basupati-jaya-dipa','Basupati Jaya Dipa');
            INSERT INTO companies(id,slug,name) VALUES (266901,'super-batu-bata','Super Batu Bata');
            INSERT INTO companies(id,slug,name) VALUES (266906,'super-bata-ringan','Super Bata Ringan');
            INSERT INTO companies(id,slug,name) VALUES (266913,'super-bata','Super Bata');
            INSERT INTO companies(id,slug,name) VALUES (267193,'citra-supplier-batam','Citra Supplier Batam');
            INSERT INTO companies(id,slug,name) VALUES (267227,'supraadi-bangunpersada','Supraadi Bangunpersada');
            INSERT INTO companies(id,slug,name) VALUES (268134,'batam-super-stone','Batam Super Stone');
            INSERT INTO companies(id,slug,name) VALUES (268457,'provision-supply-batam','Provision Supply Batam');
            INSERT INTO companies(id,slug,name) VALUES (269163,'japan-medical-supply-batam','Japan Medical Supply Batam');
            INSERT INTO companies(id,slug,name) VALUES (269528,'batam-trimasupra-elektronika','Batam Trimasupra Elektronika');
            INSERT INTO companies(id,slug,name) VALUES (270397,'super-batubara','Super Batubara');
            INSERT INTO companies(id,slug,name) VALUES (271561,'general-supplier-batam','General Supplier Batam');
            INSERT INTO companies(id,slug,name) VALUES (271875,'super-bond-batam','Super Bond Batam');
            INSERT INTO companies(id,slug,name) VALUES (272097,'supra-bangun-konstruksi','Supra Bangun Konstruksi');
            INSERT INTO companies(id,slug,name) VALUES (272313,'bauma-mini-supermarket','Bauma Mini Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (272353,'batam-oilfield-supply-services-indonesia','Batam Oilfield Supply Services Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (272518,'bauma-supermarket','Bauma Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (273112,'batam-general-supplier','Batam General Supplier');
            INSERT INTO companies(id,slug,name) VALUES (273625,'excel-superindo-batam','Excel Superindo Batam');
            INSERT INTO companies(id,slug,name) VALUES (273683,'super-jaya-batam','Super Jaya Batam');
            INSERT INTO companies(id,slug,name) VALUES (274048,'superclean-engineering-batam','Superclean Engineering Batam');
            INSERT INTO companies(id,slug,name) VALUES (274103,'suplindo-bangka-persada','Suplindo Bangka Persada');
            INSERT INTO companies(id,slug,name) VALUES (274280,'supranada-abadirekord','Supranada Abadirekord');
            INSERT INTO companies(id,slug,name) VALUES (274594,'suplindo-batam-jaya','Suplindo Batam Jaya');
            INSERT INTO companies(id,slug,name) VALUES (274694,'super-steel-batam','Super Steel Batam');
            INSERT INTO companies(id,slug,name) VALUES (275072,'super-bazaar-indonesia','Super Bazaar Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (275166,'batam-super-mandiri','Batam Super Mandiri');
            INSERT INTO companies(id,slug,name) VALUES (275257,'batavia-supply-solusindo','Batavia Supply Solusindo');
            INSERT INTO companies(id,slug,name) VALUES (275490,'batam-online-supermarket','Batam Online Supermarket');
            INSERT INTO companies(id,slug,name) VALUES (275785,'batam-mitra-suplindo','Batam Mitra Suplindo');
            INSERT INTO companies(id,slug,name) VALUES (275968,'bayu-energy-supply-cooperation','Bayu Energy Supply Cooperation');
            INSERT INTO companies(id,slug,name) VALUES (276386,'supra-bangun-perkasa','Supra Bangun Perkasa');
            INSERT INTO companies(id,slug,name) VALUES (276609,'supitmas-bayuperdana','Supitmas Bayuperdana');
            INSERT INTO companies(id,slug,name) VALUES (276663,'superland-batam','Superland Batam');
            INSERT INTO companies(id,slug,name) VALUES (277093,'parahyangan-super-abadi','Parahyangan Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (277539,'batam-marinefish-supplier','Batam Marinefish Supplier');
            INSERT INTO companies(id,slug,name) VALUES (278082,'batam-super-star','Batam Super Star');
            INSERT INTO companies(id,slug,name) VALUES (278576,'bangun-niaga-supplindo','Bangun Niaga Supplindo');
            INSERT INTO companies(id,slug,name) VALUES (280261,'super-sinar-abadi','Super Sinar Abadi');
            INSERT INTO companies(id,slug,name) VALUES (280667,'super-bangunan-indonesia','Super Bangunan Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (281489,'abadi-supiori-jaya','Abadi Supiori Jaya');
            INSERT INTO companies(id,slug,name) VALUES (281910,'bangun-kertasupra','Bangun Kertasupra');
            INSERT INTO companies(id,slug,name) VALUES (282362,'bangka-superhub-international','Bangka Superhub International');
            INSERT INTO companies(id,slug,name) VALUES (282790,'mutiarasupra-bangunutama','Mutiarasupra Bangunutama');
            INSERT INTO companies(id,slug,name) VALUES (282852,'mitra-super-abadi','Mitra Super Abadi');
            INSERT INTO companies(id,slug,name) VALUES (283464,'super-beads','Super Beads');
            INSERT INTO companies(id,slug,name) VALUES (283493,'bebas-kontraktor-supplier','Bebas Kontraktor & Supplier');
            INSERT INTO companies(id,slug,name) VALUES (283734,'price-beauty-supply','Price Beauty Supply');
            INSERT INTO companies(id,slug,name) VALUES (284466,'beebread-superfood-indonesia','Beebread Superfood Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (286577,'supreme-belting-perkasa','Supreme Belting Perkasa');
            INSERT INTO companies(id,slug,name) VALUES (286640,'super-bangunan','Super Bangunan');
            INSERT INTO companies(id,slug,name) VALUES (286656,'super-beltindo-gemilang','Super Beltindo Gemilang');
            INSERT INTO companies(id,slug,name) VALUES (286692,'tiga-belas-support-material','Tiga Belas Support Material');
            INSERT INTO companies(id,slug,name) VALUES (287751,'supriyono-tiga-belas-produksi','Supriyono Tiga Belas Produksi');
            INSERT INTO companies(id,slug,name) VALUES (288582,'supra-benelli-motosport','Supra Benelli Motosport');
            INSERT INTO companies(id,slug,name) VALUES (288662,'super-metal-abadi','Super Metal Abadi');
            INSERT INTO companies(id,slug,name) VALUES (289077,'belrey-suptech-indonesia','Belrey Suptech Indonesia');
            INSERT INTO companies(id,slug,name) VALUES (289158,'benih-super-sakti','Benih Super Sakti');
            INSERT INTO companies(id,slug,name) VALUES (290437,'benz-cahaya-suprana','Benz Cahaya Suprana');
            INSERT INTO companies(id,slug,name) VALUES (291657,'guna-supraindo-bentara','Guna Supraindo Bentara');
            INSERT INTO companies(id,slug,name) VALUES (292719,'super-metal-bangka-jaya-abadi','Super Metal Bangka Jaya Abadi');
            INSERT INTO companies(id,slug,name) VALUES (293311,'supradera-bermitra','Supradera Bermitra');");
    }
}
